### ISSUE TITLE
Do you have 'necked_tensile_specimen.png'?

### ISSUE THREAD

**Issue by JohnNehls** [matplotlib/sample_data#1]
Dr. Perez,

Thank you for, among many other things, maintaining this repository! 

*\* update *\* I found the file I was looking for and attatched it below if you'd like to add it to this collection of sample data *********
![necked_tensile_specimen](https://cloud.githubusercontent.com/assets/15070797/10494860/a0aae652-726d-11e5-9de2-2a4eed2f1df9.png)

***\* begin initial comment ***
I am looking for 'necked_tensile_specimen.png' used in the matplotlib example here:     http://matplotlib.org/examples/images_contours_and_fields/interpolation_none_vs_nearest.html

Do you happen to have it around?

Thank you for your time.
~John

PS. In case you are wondering, I am interested in the example because it appears that the coordinates of the pixles are set in the data and imshow respects this when it is called, and, somehow, grid lines are drawn, delineating the data. I am interested in seeing the arrangement of data that achieves this.

**Comment by mdboom** [comment]
It is here: https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/mpl-data/sample_data/necked_tensile_specimen.png
